# Generated by Django 4.0.6 on 2022-12-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
